Forum/Controllers/TagController.cs
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult List(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


            }

            using (var database = new ForumDbContext())
            {
                var questions = database.Tags
                    .Include(t => t.Posts.Select(a => a.Tags))
                    .Include(t => t.Posts.Select(a => a.Author))
                    .FirstOrDefault(x => x.Id == id)
                    .Posts
                    .ToList();


                return View(questions);
            }

        }


    }
}

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Forum", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Forum/Views/Shared/_ListAnswersCreatePost.cshtml
@{
                Forum.Models.PostViewModel post = new Forum.Models.PostViewModel();
}
@using (Html.BeginForm("CreatePost", "Post", new { id = ViewBag.question.PostId, page = ViewBag.pages }, FormMethod.Post, new { @class = "form-horizontal" }))
{
@Html.AntiForgeryToken()
@Html.ValidationSummary("", new { @class = "text-danger" })

@Html.HiddenFor(m => post.CategoryId, new { Value = ViewBag.categoryId })

<div class="form-group">
    @Html.LabelFor(m => post.Title, new { @class = "control-label col-sm-2" })
    <div class="col-sm-8">
        @Html.TextBoxFor(m => post.Title, new { @Value = "Re:" + ViewBag.question.Title, @class = "form-control", Style = " max-width: 980px;" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => post.Content, new { @class = "control-label col-sm-2" })
    <div class="col-sm-8">
        @Html.TextAreaFor(m => post.Content, new { @class = "form-control", @rows = "7", Style = " max-width: 980px;" })
    </div>
</div>

<div class="form-group">
    <div class="col-sm-6 col-sm-offset-5">
        @Html.ActionLink("Cancel", "ListQuestions", "Post", null, new { @class = "btn btn-default" })
        <input type="submit" value="Post" class="btn btn-success" />

    </div>
</div>
}

Forum/Views/Shared/_ListAnswersPartial.cshtml
@model Forum.Models.Post


@{bool Isquestion = (bool)@ViewData["question"];}
 

            <div class="row">

                <div class="col-sm-10">

                    <div class="row">
                        <div class="col-sm-12">
                            <h3>@Model.Title</h3>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            @Model.Content
                        </div>
                    </div>

                    @if (Isquestion)
                    {
                    <div class="row">

                        <div class="col-sm-1">
                            Tags
                        </div>
                        <div class="col-sm-11 pull-left">
                            @foreach (var tag in Model.Tags)
                            {
                                @Html.ActionLink((string)tag.Name, "List", "Tag", new { @id = tag.Id }, new { @class = "btn btn-default btn-xs" })
                            }
                        </div>


                    </div>
                    }


                    @if (User.IsInRole("Admin") || Model.isAuthor(User.Identity.Name))
                    {
                        <div class="row" style="margin-top:5px">
                            <div class="col-sm-2">
                                @Html.ActionLink("Edit", "Edit", "Post", new { @id = Model.PostId }, new { @class = "btn btn-success btn-xs" })
                                @Html.ActionLink("Delete", "Delete", "Post", new { @id = Model.PostId }, new { @class = "btn btn-danger btn-xs" })
                            </div>
                        </div>
                    }



                </div>


                <div class="col-sm-2">


                    <div class="row " align="center">
                        @if (Model.AuthorId != null)
                        {
                            var imgUrl = Url.Content("~/Content/images/profile/" + Model.Author.UserName + ".png") + "?time=" + DateTime.Now.ToString();
                            <object data="@imgUrl" type="image/png" height="50" width="50">
                                <img src="~/Content/images/Smiley.svg.png" height="50" width="50" />
                            </object>
                        }
                    </div>

                    <div class="row" align="center">

                        @if (Model.AuthorId != null)
                        {
                            @Html.ActionLink(Model.Author.FullName, "Details", "Account", new { @id = Model.Author.Id }, null)
                        }

                    </div>


                </div>



            </div>

Forum/Views/Shared/_ListQuestionsPartial.cshtml
@model Forum.Models.Post

@{int j = (int)@ViewData["answersCount"];}
 
    
    <div class="row">
        <div class="col-sm-1" align="center"><img src="~/Content/images/topic.png" /></div>

        <div class="col-sm-7">
            <div class="row">
                @Html.ActionLink(Model.Title, "ListAnswers", "Post", new { @id = Model.PostId, @page = 1 }, null)
            </div>

            @if (User.IsInRole("Admin") || Model.isAuthor(User.Identity.Name))
            {
                <div class="row">

                    <div class="col-sm-3">
                        @Html.ActionLink("Edit", "Edit", "Post", new { @id = Model.PostId }, new { @class = "btn btn-success btn-xs" })
                        @Html.ActionLink("Delete", "Delete", "Post", new { @id = Model.PostId }, new { @class = "btn btn-danger btn-xs" })
                    </div>

                </div>

            }
        </div>
        
        <div class="col-sm-1">@j.ToString()</div>
     

        <div class="col-sm-1">@Model.Views</div>
        <div class="col-sm-1">@Html.ActionLink(Model.Author.FullName, "Details", "Account", new { @id = Model.Author.Id }, null)</div>

        <div class="col-sm-1">



            @{var imgUrl = Url.Content("~/Content/images/profile/" + Model.Author.UserName + ".png") + "?time=" + DateTime.Now.ToString(); }

            <object data="@imgUrl" type="image/png" height="30" width="30">
                <img src="~/Content/images/Smiley.svg.png" height="30" width="30" />
            </object>



        </div>

    </div>
                

Forum/Views/Shared/_NavigationAndPagingListAnswers.cshtml
<div class="row">
    <div class="container">
        <div class="well">
            <div class="row">

                <div class="col-sm-2">
                    @Html.ActionLink("Comment", "ListAnswers", "Post", new { id = ViewBag.question.PostId, reply = 1, page = @ViewBag.page }, new { @class = "btn btn-warning" })


                </div>


                <div class="col-sm-4">
                    @{
                        int catId = (int)ViewBag.question.CategoryId;
                        var CategoryName = new Forum.Models.ForumDbContext().Categories.Where(x => x.Id == catId).FirstOrDefault().Name;
                    }

                    <div class="col-sm-6">

                        @Html.ActionLink("Categories", "Index", "Home")

                    </div>

                    <div class="col-sm-6">

                        @Html.ActionLink(CategoryName, "ListQuestions", "Post", new { @categoryId = catId, @page = 1 }, null)

                    </div>



                </div>


                <div class="col-sm-6" style="text-align:right">
                    <ul class="pagination">
                        @{
                            int prevPage = 0;
                            List<int> pagingList = ViewBag.pagingElems;

                        }

                        @for (int i = 0; i < pagingList.Count(); i++)
                        {
                            prevPage = pagingList[i];

                            <li>
                                @Html.ActionLink(pagingList[i].ToString(), "ListAnswers", "Post", new { @id = ViewBag.question.PostId, @page = pagingList[i] }, null)
                            </li>


                            if (i < pagingList.Count() - 1 && pagingList[i + 1] != pagingList[i] + 1)
                            {
                                <li>@Html.ActionLink("...", "Index", "Home") </li>

                            }


                        }
                    </ul>

                </div>
            </div>
        </div>
    </div>

</div>

Forum/Views/Shared/_NavigationAndPagingListQuestions.cshtml
<div class="row">

    <div class="col-sm-2">
        @Html.ActionLink("New Topic", "CreatePost", "Post", new { @categoryid = ViewBag.categoryId }, new { @class = "btn btn-warning" })
    </div>

    @{
        int catId = (int)ViewBag.categoryId;
        var CategoryName = new Forum.Models.ForumDbContext().Categories.Where(x => x.Id == catId).FirstOrDefault().Name;
    }

    <div class="col-sm-2">

        @Html.ActionLink("Categories", "Index", "Home")

    </div>

    <div class="col-sm-2">

        @Html.ActionLink(CategoryName, "ListQuestions", "Post", new { @categoryId = ViewBag.categoryId, @page = 1 }, null)

    </div>


    <div class="col-sm-4 col-sm-offset-2" style="text-align:right">

        <ul class="pagination">
            @{
                int prevPage = 0;
                List<int> pagingList = ViewBag.pagingElems;
            }

            @for (int i = 0; i < pagingList.Count(); i++)
            {
                prevPage = pagingList[i];
                <li>
                    @Html.ActionLink(pagingList[i].ToString(), "ListQuestions", "Post", new { @categoryId = ViewBag.categoryId, @page = pagingList[i] }, null)
                </li>
                if (i < pagingList.Count() - 1 && pagingList[i + 1] != pagingList[i] + 1)
                {
                    <li>@Html.ActionLink("...", "Index", "Home") </li>

                }
            }
        </ul>

    </div>

</div>